memory_limit = 512M
upload_max_filesize = 100M
post_max_size = 100M
max_execution_time = 600

; Huge boost for Docker on Windows NTFS File I/O
realpath_cache_size = 8192K
realpath_cache_ttl = 600

; PHP-FPM timeout settings
default_socket_timeout = 60

