services:
  mysql:
    image: mysql:8.0
    container_name: laravel_emp_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: wibo2909
      MYSQL_DATABASE: laravel_emp
      MYSQL_USER: laravel
      MYSQL_PASSWORD: wibo2909
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_emp_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pwibo2909" ]
      interval: 5s
      timeout: 5s
      retries: 10

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: laravel_emp_pma
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 0
      UPLOAD_LIMIT: 300M
    depends_on:
      - mysql
    networks:
      - laravel_emp_net

  ngrok:
    image: ngrok/ngrok:latest
    container_name: laravel_emp_ngrok
    restart: unless-stopped
    command:
      - "http"
      - "--url=hatchet-improving-creed.ngrok-free.dev"
      - "host.docker.internal:8005"
    environment:
      NGROK_AUTHTOKEN: 3IeB7lyTKqOa8YDTxBb1nZTXwMa_2FXS5PTocUEaQz5j7NQAc
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  mysql_data:
    driver: local

networks:
  laravel_emp_net:
    driver: bridge
